# Site settings
title: ClojureScript
description: > # this means to ignore newlines until "baseurl:"
  The Clojure to JavaScript compiler.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cljsinfo.github.io" # the base hostname & protocol for your site

# Build settings
keep_files: ["README.md", ".git"] # When clobbering the site destination, keep the selected files
exclude: ['Gemfile', 'Gemfile.lock'] # don't process these when generating the site
markdown: RedcarpetCLJS # wraps redcarpet with some cljs things (see _plugins/)

# RedCarpet markdown parser
# (tuned to be like GitHub-Flavored Markdown)
# (more options here: https://github.com/vmg/redcarpet/blob/v3.2.2/README.markdown#and-its-like-really-simple-to-use)
redcarpet:
  extensions: [
    "autolink",            # parse links even when they are not enclosed in <> characters
    "fenced_code_blocks",  # parse fenced code blocks, PHP-Markdown style
    "tables",              # parse tables, PHP-Markdown style.
    "strikethrough",       # parse strikethrough, PHP-Markdown style
    "no_intra_emphasis"   # do not parse emphasis inside of words. Strings such as foo_bar_baz
  ]

